export default {
  INITIALIZED: 'INITIALIZED',
  NETWORK_CHANGED: 'NETWORK_CHANGED',
  CONTRACT_FETCHED: 'CONTRACT_FETCHED',
  CONTRACT_UNKNOWN: 'CONTRACT_UNKNOWN',
  CONTRACT_FETCH_FAILED: 'CONTRACT_FETCH_FAILED',
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  BALANCE_FAILED: 'BALANCE_FAILED',
  POOL_NAME_FETCHED: 'POOL_NAME_FETCHED',
  RISK_FREE_POOL_FETCHED: 'RISK_FREE_POOL_FETCHED',
  RISKY_POOL_FETCHED: 'RISKY_POOL_FETCHED',
  POSITION_FETCHED: 'POSITION_FETCHED',
}
